(in-package :common-graphics-user)
(defun is-null-string (str)
  (string= str "")
  )
(defun is-not-null-string (str)
  (not (is-null-string str))
  )
(load "E:\\programs\\uipreview\\Debug\\uipreview.dll")
(ff:def-foreign-call (HostToNetShort "HostToNetShort") (s))
