(in-package :common-graphics-user)
(defun get-project-num ()
  (uie:project-num)
  )
(defun contain-project-name? (name)
  (uie:is-contain-project-name name)
  )
(defun contain-project-path? (path)
  (uie:is-contain-project-path path)
  )
(defun get-all-project-name ()
  (uie:list-project-name)
  )
(defun add-project (name path)
  (uie:add-project name path)
  )