PLAT_CC  = gcc
PLAT_CPP = g++
PLAT_AR  = ar
RM = rm -f
SDKDIR = /home/luwei/program/powervr/SDKPackage
PLATFORM = LinuxPC
SEENG_DIR = /home/luwei/program/streamserver_git/test-server/SEHome/seengine/src
OUTNAME = SEDemo
## X11 lib define
X11_LIBS = -lX11 -lXau
WS = X11
X11_INC = /usr/include/X11
LIBDIR_FLAGS = -Wl,--rpath-link=$(SDKDIR)/Builds/OGLES2/$(PLATFORM)/Lib \
               -L$(SDKDIR)/Builds/OGLES2/$(PLATFORM)/Lib
PLAT_CFLAGS = -DBUILD_OGLES2 -DDEBUG -DGLES_20 -g

PLAT_INC = $(SDKDIR)/Builds/OGLES2/Include \
	   $(X11_INC) 

PLAT_OBJPATH = $(PLATFORM)/$(WS)
PLAT_LINK = $(LIBDIR_FLAGS) -lEGL -lGLESv2 $(X11_LIBS)
INCLUDES += -I$(SDKDIR)/Shell  \
			-I$(SDKDIR)/Shell/API/KEGL \
			-I$(SDKDIR)/Shell/OS/LinuxX11 \
			-I$(SEENG_DIR) \
			-I$(SEENG_DIR)/export \
			-I$(SEENG_DIR)/command \
			$(addprefix -I, $(PLAT_INC))

VPATH +=  ../ : \
	  ../command : \
	  ../export : \
	  $(SDKDIR)/Shell            : \
	  $(SDKDIR)/Shell/API/KEGL   : \
	  $(SDKDIR)/Shell/OS/LinuxX11
DEPEND_FLAG = $(PLAT_CFLAGS) $(INCLUDES)
##SRC_LUA = lapi.c lauxlib.c lbaselib.c lcode.c ldblib.c ldebug.c ldo.c  ldump.c lfunc.c  lgc.c linit.c liolib.c llex.c \
##	  lmathlib.c lmem.c loadlib.c lobject.c lopcodes.c loslib.c lparser.c lstate.c lstring.c lstrlib.c ltable.c ltablib.c ltm.c \
##	  lundump.c lvm.c lzio.c print.c

SRCS_CPP = SE_Buffer.cpp   \
	SE_DataTransfer.cpp  \
	SE_ImageData.cpp      \
	SE_Mesh.cpp           \
	SE_ResFileHeader.cpp   \
	SE_Camera.cpp         \
	SE_File.cpp          \
	SE_IO.cpp            \
	SE_MeshSimObject.cpp  \
	SE_ResourceManager.cpp \
	SE_TextureCoordData.cpp \
	SE_Command.cpp         \
	SE_Geometry3D.cpp    \
	SE_Log.cpp           \
	SE_Object.cpp         \
	SE_SceneManager.cpp    \
	SE_Texture.cpp          \
	SE_CommandFactory.cpp  \
	SE_Geometry.cpp        \
	SE_MaterialData.cpp    \
	SE_Quat.cpp   \
	SE_ShaderProgram.cpp \
	SE_Time.cpp          \
	SE_GeometryData.cpp  \
	SE_Application.cpp    \
	SE_Common.cpp          \
	SE_Math.cpp     \
	SE_RenderManager.cpp  \
	SE_SimObject.cpp   \
	SE_Utils.cpp \
	SE_BoundingVolume.cpp   \
	SE_CommonNode.cpp    \
	SE_ID.cpp         \
	SE_Matrix.cpp     \
	SE_RenderUnit.cpp  \
	SE_Spatial.cpp    \
	SE_Vector.cpp \
	SE_Ase.cpp \
	SE_SystemCommand.cpp \
	SE_SystemCommandFactory.cpp \
	SE_InputEvent.cpp \
	SE_InputManager.cpp \
	SE_MotionEventCamera.cpp \
	SE_SpatialTravel.cpp \
	SEDemo.cpp \
	PVRShell.cpp \
	PVRShellAPI.cpp \
	PVRShellOS.cpp
SRCS = $(shell for d in $(SRCS_C) ; do find ../ -name $$d ; done)
SRCS += $(shell for d in $(SRCS_CPP) ; do find ../ -name $$d ; done)
OBJ_C = $(SRCS_C:.c=.o)
OBJ_CPP = $(SRCS_CPP:.cpp=.o)
OBJECTS += $(OBJ_C)
OBJECTS += $(OBJ_CPP)

$(OUTNAME): $(OBJ_C) $(OBJ_CPP) depend
	$(PLAT_CPP) -o $(OUTNAME) $(OBJECTS) $(PLAT_LINK)

%.o: %.c
	$(PLAT_CC) -c $(PLAT_CFLAGS) $(INCLUDES) $< -o $@

%.o: %.cpp
	@echo $<
	@echo $@
	$(PLAT_CPP) -c $(PLAT_CFLAGS) $(INCLUDES) $< -o $@

depend: 
	makedepend -- $(DEPEND_FLAG) -- $(SRCS)

print_info:
	@echo $(OBJECTS)
	@echo $(OBJ_CPP)
	@echo $(OUTNAME)
	@echo $(INCLUDES)
	@echo $(PLAT_CFLAGS)
	@echo $(VPATH)
	@echo $(SRCS)
clean:
	$(RM) $(OBJECTS) $(OUTNAME)
# DO NOT DELETE
