(in-package :uie)
(setf a (list-project-path))
(assert (eql a nil))
(setf b (list-project-path))
(assert (equal b nil))
(assert (equal (project-num) 0))

(add-project "aa" "C:\\ppp")
(setf a (list-project-path))
(setf b (list-project-name))
(assert (string-equal (car a) "C:\\ppp"))
(assert (string-equal (car b) "aa"))
(assert (equal (project-num) 1))
