CC = g++
RM = rm -f
SRCS = SE_Vector.c \
		   SE_Math.c \
		   SE_Matrix.c \
		   SE_Quat.c \
		   SE_Memory.c \
		   SE_Element.c \
		   SE_String.c \
		   SE_List.c \
		   SE_HashMap.c \
		   SE_Log.c \
		   SE_Utils.c \
		   SE_GeometryData.c \
		   SE_Spatial.c \
		   SE_BoundingVolume.c \
		   SE_ResourceManager.c \
		   SE_Geometry3D.c \
		   SE_RenderState.c \
		   SE_World.c \
		   SE_Camera.c \
		   SE_Script.c \
		   SE_Input.c \
		   SE_Init.c \
		   SE_SaveState.c \
		   SE_AABB.c \
		   SE_Sphere.c \
		   SE_GeometryIntersect.c \
		   ./renderer/SE_TextureID.c \
		   ./renderer/SE_Renderer.c \
		   ./cscript/hashmap.c \
		   ./cscript/acc.c \
		   ./ase/aselib.c \
		   main.c

OBJ_FILE = $(SRCS:.c=.o)
OUTPUT_NAME = seapp
INCLUDE_PATH = -I./ -I../ -I/usr/include -I/usr/include/SDL
INPUT_LIB = -L/usr/lib -lm -lGL -lGLU `sdl-config --libs`
CFLAGS = -g $(INCLUDE_PATH)
all: $(OBJ_FILE) depend
	$(CC) $(INPUT_LIB) $(OBJ_FILE) -o $(OUTPUT_NAME)
depend: 
	makedepend -- $(CFLAGS) -- $(SRCS)
%.o: %.c
	$(CC) -c $(CFLAGS) $< -o $@ 
clean:
	$(RM) $(OBJ_FILE) $(OUTPUT_NAME)
# DO NOT DELETE

SE_Vector.o: SE_Vector.h SE_Common.h /usr/include/assert.h
SE_Vector.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Vector.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Vector.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Vector.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Vector.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Vector.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Vector.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Vector.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Vector.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Vector.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Vector.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Vector.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Vector.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Vector.o: SE_Math.h
SE_Math.o: SE_Math.h SE_Common.h /usr/include/assert.h
SE_Math.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Math.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Math.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Math.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Math.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Math.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Math.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Math.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Math.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Math.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Math.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Math.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Math.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Math.o: /usr/include/math.h /usr/include/bits/huge_val.h
SE_Math.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
SE_Matrix.o: SE_Matrix.h SE_Vector.h SE_Common.h /usr/include/assert.h
SE_Matrix.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Matrix.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Matrix.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Matrix.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Matrix.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Matrix.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Matrix.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Matrix.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Matrix.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Matrix.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Matrix.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Matrix.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Matrix.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Matrix.o: SE_Math.h
SE_Quat.o: SE_Quat.h SE_Vector.h SE_Common.h /usr/include/assert.h
SE_Quat.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Quat.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Quat.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Quat.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Quat.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Quat.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Quat.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Quat.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Quat.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Quat.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Quat.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Quat.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Quat.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Quat.o: SE_Matrix.h SE_Math.h
SE_Memory.o: SE_Memory.h SE_Common.h /usr/include/assert.h
SE_Memory.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Memory.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Memory.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Memory.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Memory.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Memory.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Memory.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Memory.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Memory.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Memory.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Memory.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Memory.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Memory.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Element.o: SE_Element.h SE_Common.h /usr/include/assert.h
SE_Element.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Element.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Element.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Element.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Element.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Element.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Element.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Element.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Element.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Element.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Element.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Element.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Element.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Element.o: SE_String.h SE_Memory.h
SE_String.o: SE_String.h SE_Common.h /usr/include/assert.h
SE_String.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_String.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_String.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_String.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_String.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_String.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_String.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_String.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_String.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_String.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_String.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_String.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_String.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_String.o: SE_Memory.h
SE_List.o: SE_List.h SE_Common.h /usr/include/assert.h
SE_List.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_List.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_List.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_List.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_List.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_List.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_List.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_List.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_List.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_List.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_List.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_List.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_List.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_List.o: SE_Element.h SE_String.h SE_Memory.h
SE_HashMap.o: SE_HashMap.h SE_Common.h /usr/include/assert.h
SE_HashMap.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_HashMap.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_HashMap.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_HashMap.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_HashMap.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_HashMap.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_HashMap.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_HashMap.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_HashMap.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_HashMap.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_HashMap.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_HashMap.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_HashMap.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_HashMap.o: SE_Element.h SE_String.h SE_Memory.h SE_Log.h
SE_HashMap.o: /usr/include/errno.h /usr/include/bits/errno.h
SE_HashMap.o: /usr/include/linux/errno.h /usr/include/asm/errno.h
SE_HashMap.o: /usr/include/asm-generic/errno.h
SE_HashMap.o: /usr/include/asm-generic/errno-base.h
SE_Log.o: SE_Log.h SE_Common.h /usr/include/assert.h /usr/include/features.h
SE_Log.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
SE_Log.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
SE_Log.o: /usr/include/stdlib.h /usr/include/sys/types.h
SE_Log.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
SE_Log.o: /usr/include/time.h /usr/include/endian.h
SE_Log.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
SE_Log.o: /usr/include/sys/select.h /usr/include/bits/select.h
SE_Log.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
SE_Log.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
SE_Log.o: /usr/include/alloca.h /usr/include/string.h /usr/include/stdio.h
SE_Log.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
SE_Log.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Utils.o: SE_Utils.h SE_Vector.h SE_Common.h /usr/include/assert.h
SE_Utils.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Utils.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Utils.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Utils.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Utils.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Utils.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Utils.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Utils.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Utils.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Utils.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Utils.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Utils.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Utils.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Utils.o: SE_Matrix.h SE_Quat.h SE_Math.h SE_Log.h SE_Memory.h
SE_GeometryData.o: SE_GeometryData.h SE_Common.h /usr/include/assert.h
SE_GeometryData.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_GeometryData.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_GeometryData.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_GeometryData.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_GeometryData.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_GeometryData.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_GeometryData.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_GeometryData.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_GeometryData.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_GeometryData.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_GeometryData.o: /usr/include/string.h /usr/include/stdio.h
SE_GeometryData.o: /usr/include/libio.h /usr/include/_G_config.h
SE_GeometryData.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
SE_GeometryData.o: /usr/include/bits/sys_errlist.h SE_Vector.h SE_Memory.h
SE_GeometryData.o: SE_Log.h
SE_Spatial.o: SE_Spatial.h SE_Common.h /usr/include/assert.h
SE_Spatial.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Spatial.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Spatial.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Spatial.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Spatial.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Spatial.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Spatial.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Spatial.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Spatial.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Spatial.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Spatial.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Spatial.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Spatial.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Spatial.o: SE_Vector.h SE_BoundingVolume.h SE_Geometry3D.h SE_Quat.h
SE_Spatial.o: SE_Matrix.h SE_AABB.h SE_Sphere.h SE_RenderState.h SE_String.h
SE_Spatial.o: SE_ResourceManager.h SE_GeometryData.h SE_HashMap.h
SE_Spatial.o: SE_Element.h SE_Script.h ./cscript/acc.h /usr/include/stdint.h
SE_Spatial.o: /usr/include/bits/wchar.h ./renderer/SE_TextureID.h
SE_Spatial.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
SE_Spatial.o: /usr/include/inttypes.h SE_List.h SE_Memory.h SE_Utils.h
SE_BoundingVolume.o: SE_BoundingVolume.h SE_Common.h /usr/include/assert.h
SE_BoundingVolume.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_BoundingVolume.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_BoundingVolume.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_BoundingVolume.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_BoundingVolume.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_BoundingVolume.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_BoundingVolume.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_BoundingVolume.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_BoundingVolume.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_BoundingVolume.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_BoundingVolume.o: /usr/include/string.h /usr/include/stdio.h
SE_BoundingVolume.o: /usr/include/libio.h /usr/include/_G_config.h
SE_BoundingVolume.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
SE_BoundingVolume.o: /usr/include/bits/sys_errlist.h SE_Geometry3D.h
SE_BoundingVolume.o: SE_Vector.h SE_Quat.h SE_Matrix.h SE_AABB.h SE_Sphere.h
SE_BoundingVolume.o: SE_GeometryIntersect.h
SE_ResourceManager.o: SE_ResourceManager.h SE_Common.h /usr/include/assert.h
SE_ResourceManager.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_ResourceManager.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_ResourceManager.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_ResourceManager.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_ResourceManager.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_ResourceManager.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_ResourceManager.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_ResourceManager.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_ResourceManager.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_ResourceManager.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_ResourceManager.o: /usr/include/string.h /usr/include/stdio.h
SE_ResourceManager.o: /usr/include/libio.h /usr/include/_G_config.h
SE_ResourceManager.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
SE_ResourceManager.o: /usr/include/bits/sys_errlist.h SE_GeometryData.h
SE_ResourceManager.o: SE_Vector.h SE_HashMap.h SE_Element.h SE_String.h
SE_ResourceManager.o: SE_Script.h ./cscript/acc.h /usr/include/stdint.h
SE_ResourceManager.o: /usr/include/bits/wchar.h ./renderer/SE_TextureID.h
SE_ResourceManager.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
SE_ResourceManager.o: /usr/include/inttypes.h SE_Memory.h SE_Log.h SE_Utils.h
SE_ResourceManager.o: SE_Matrix.h SE_Quat.h
SE_Geometry3D.o: SE_Geometry3D.h SE_Vector.h SE_Common.h
SE_Geometry3D.o: /usr/include/assert.h /usr/include/features.h
SE_Geometry3D.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
SE_Geometry3D.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
SE_Geometry3D.o: /usr/include/stdlib.h /usr/include/sys/types.h
SE_Geometry3D.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
SE_Geometry3D.o: /usr/include/time.h /usr/include/endian.h
SE_Geometry3D.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
SE_Geometry3D.o: /usr/include/sys/select.h /usr/include/bits/select.h
SE_Geometry3D.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
SE_Geometry3D.o: /usr/include/sys/sysmacros.h
SE_Geometry3D.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Geometry3D.o: /usr/include/string.h /usr/include/stdio.h
SE_Geometry3D.o: /usr/include/libio.h /usr/include/_G_config.h
SE_Geometry3D.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
SE_Geometry3D.o: /usr/include/bits/sys_errlist.h SE_Math.h
SE_RenderState.o: SE_RenderState.h SE_Common.h /usr/include/assert.h
SE_RenderState.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_RenderState.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_RenderState.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_RenderState.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_RenderState.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_RenderState.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_RenderState.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_RenderState.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_RenderState.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_RenderState.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_RenderState.o: /usr/include/string.h /usr/include/stdio.h
SE_RenderState.o: /usr/include/libio.h /usr/include/_G_config.h
SE_RenderState.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
SE_RenderState.o: /usr/include/bits/sys_errlist.h SE_String.h
SE_RenderState.o: SE_ResourceManager.h SE_GeometryData.h SE_Vector.h
SE_RenderState.o: SE_HashMap.h SE_Element.h SE_Script.h ./cscript/acc.h
SE_RenderState.o: /usr/include/stdint.h /usr/include/bits/wchar.h
SE_RenderState.o: ./renderer/SE_TextureID.h /usr/include/GL/gl.h
SE_RenderState.o: /usr/include/GL/glext.h /usr/include/inttypes.h
SE_World.o: SE_World.h SE_Camera.h SE_Common.h /usr/include/assert.h
SE_World.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_World.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_World.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_World.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_World.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_World.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_World.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_World.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_World.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_World.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_World.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_World.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_World.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_World.o: SE_Geometry3D.h SE_Vector.h SE_BoundingVolume.h SE_Quat.h
SE_World.o: SE_Matrix.h SE_AABB.h SE_Sphere.h SE_List.h SE_Element.h
SE_World.o: SE_String.h SE_Spatial.h SE_RenderState.h SE_ResourceManager.h
SE_World.o: SE_GeometryData.h SE_HashMap.h SE_Script.h ./cscript/acc.h
SE_World.o: /usr/include/stdint.h /usr/include/bits/wchar.h
SE_World.o: ./renderer/SE_TextureID.h /usr/include/GL/gl.h
SE_World.o: /usr/include/GL/glext.h /usr/include/inttypes.h SE_Input.h
SE_World.o: SE_SaveState.h
SE_Camera.o: SE_Camera.h SE_Common.h /usr/include/assert.h
SE_Camera.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Camera.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Camera.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Camera.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Camera.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Camera.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Camera.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Camera.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Camera.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Camera.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Camera.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Camera.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Camera.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Camera.o: SE_Geometry3D.h SE_Vector.h SE_BoundingVolume.h SE_Quat.h
SE_Camera.o: SE_Matrix.h SE_AABB.h SE_Sphere.h SE_Log.h
SE_Script.o: SE_Script.h SE_Common.h /usr/include/assert.h
SE_Script.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Script.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Script.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Script.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Script.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Script.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Script.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Script.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Script.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Script.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Script.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Script.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Script.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Script.o: SE_String.h ./cscript/acc.h /usr/include/stdint.h
SE_Script.o: /usr/include/bits/wchar.h SE_Utils.h SE_Vector.h SE_Matrix.h
SE_Script.o: SE_Quat.h SE_Spatial.h SE_BoundingVolume.h SE_Geometry3D.h
SE_Script.o: SE_AABB.h SE_Sphere.h SE_RenderState.h SE_ResourceManager.h
SE_Script.o: SE_GeometryData.h SE_HashMap.h SE_Element.h
SE_Script.o: ./renderer/SE_TextureID.h /usr/include/GL/gl.h
SE_Script.o: /usr/include/GL/glext.h /usr/include/inttypes.h SE_List.h
SE_Script.o: SE_Log.h ./renderer/SE_Renderer.h SE_World.h SE_Camera.h
SE_Script.o: SE_Input.h SE_SaveState.h /usr/include/dlfcn.h
SE_Script.o: /usr/include/bits/dlfcn.h
SE_Input.o: SE_Input.h SE_Common.h /usr/include/assert.h
SE_Input.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Input.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Input.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Input.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Input.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Input.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Input.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Input.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Input.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Input.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Input.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Input.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Input.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Input.o: SE_Vector.h SE_World.h SE_Camera.h SE_Geometry3D.h
SE_Input.o: SE_BoundingVolume.h SE_Quat.h SE_Matrix.h SE_AABB.h SE_Sphere.h
SE_Input.o: SE_List.h SE_Element.h SE_String.h SE_Spatial.h SE_RenderState.h
SE_Input.o: SE_ResourceManager.h SE_GeometryData.h SE_HashMap.h SE_Script.h
SE_Input.o: ./cscript/acc.h /usr/include/stdint.h /usr/include/bits/wchar.h
SE_Input.o: ./renderer/SE_TextureID.h /usr/include/GL/gl.h
SE_Input.o: /usr/include/GL/glext.h /usr/include/inttypes.h SE_SaveState.h
SE_Input.o: SE_Log.h SE_Memory.h
SE_Init.o: SE_Init.h SE_Common.h /usr/include/assert.h
SE_Init.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Init.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Init.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Init.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Init.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Init.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Init.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Init.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Init.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Init.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Init.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Init.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Init.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Init.o: /usr/include/math.h /usr/include/bits/huge_val.h
SE_Init.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
SE_Init.o: SE_ResourceManager.h SE_GeometryData.h SE_Vector.h SE_HashMap.h
SE_Init.o: SE_Element.h SE_String.h SE_Script.h ./cscript/acc.h
SE_Init.o: /usr/include/stdint.h /usr/include/bits/wchar.h
SE_Init.o: ./renderer/SE_TextureID.h /usr/include/GL/gl.h
SE_Init.o: /usr/include/GL/glext.h /usr/include/inttypes.h SE_Spatial.h
SE_Init.o: SE_BoundingVolume.h SE_Geometry3D.h SE_Quat.h SE_Matrix.h
SE_Init.o: SE_AABB.h SE_Sphere.h SE_RenderState.h SE_List.h SE_Log.h
SE_Init.o: SE_World.h SE_Camera.h SE_Input.h SE_SaveState.h cscript/acc.h
SE_Init.o: /usr/include/ctype.h /usr/include/dlfcn.h
SE_Init.o: /usr/include/bits/dlfcn.h ./renderer/SE_Renderer.h
SE_SaveState.o: SE_SaveState.h SE_Common.h /usr/include/assert.h
SE_SaveState.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_SaveState.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_SaveState.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_SaveState.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_SaveState.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_SaveState.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_SaveState.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_SaveState.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_SaveState.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_SaveState.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_SaveState.o: /usr/include/string.h /usr/include/stdio.h
SE_SaveState.o: /usr/include/libio.h /usr/include/_G_config.h
SE_SaveState.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
SE_SaveState.o: /usr/include/bits/sys_errlist.h SE_Vector.h
SE_AABB.o: SE_AABB.h SE_Common.h /usr/include/assert.h
SE_AABB.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_AABB.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_AABB.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_AABB.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_AABB.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_AABB.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_AABB.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_AABB.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_AABB.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_AABB.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_AABB.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_AABB.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_AABB.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_AABB.o: SE_Vector.h SE_Matrix.h
SE_Sphere.o: SE_Sphere.h SE_Common.h /usr/include/assert.h
SE_Sphere.o: /usr/include/features.h /usr/include/sys/cdefs.h
SE_Sphere.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
SE_Sphere.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
SE_Sphere.o: /usr/include/sys/types.h /usr/include/bits/types.h
SE_Sphere.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_Sphere.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_Sphere.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
SE_Sphere.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
SE_Sphere.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
SE_Sphere.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
SE_Sphere.o: /usr/include/string.h /usr/include/stdio.h /usr/include/libio.h
SE_Sphere.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_Sphere.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
SE_Sphere.o: SE_Vector.h SE_Matrix.h SE_Math.h
SE_GeometryIntersect.o: SE_GeometryIntersect.h SE_Vector.h SE_Common.h
SE_GeometryIntersect.o: /usr/include/assert.h /usr/include/features.h
SE_GeometryIntersect.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
SE_GeometryIntersect.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
SE_GeometryIntersect.o: /usr/include/stdlib.h /usr/include/sys/types.h
SE_GeometryIntersect.o: /usr/include/bits/types.h
SE_GeometryIntersect.o: /usr/include/bits/typesizes.h /usr/include/time.h
SE_GeometryIntersect.o: /usr/include/endian.h /usr/include/bits/endian.h
SE_GeometryIntersect.o: /usr/include/bits/byteswap.h
SE_GeometryIntersect.o: /usr/include/sys/select.h /usr/include/bits/select.h
SE_GeometryIntersect.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
SE_GeometryIntersect.o: /usr/include/sys/sysmacros.h
SE_GeometryIntersect.o: /usr/include/bits/pthreadtypes.h
SE_GeometryIntersect.o: /usr/include/alloca.h /usr/include/string.h
SE_GeometryIntersect.o: /usr/include/stdio.h /usr/include/libio.h
SE_GeometryIntersect.o: /usr/include/_G_config.h /usr/include/wchar.h
SE_GeometryIntersect.o: /usr/include/bits/stdio_lim.h
SE_GeometryIntersect.o: /usr/include/bits/sys_errlist.h SE_Geometry3D.h
SE_GeometryIntersect.o: SE_Sphere.h SE_Matrix.h SE_AABB.h SE_Math.h
SE_GeometryIntersect.o: SE_Memory.h
./renderer/SE_TextureID.o: ./renderer/SE_TextureID.h SE_Common.h
./renderer/SE_TextureID.o: /usr/include/assert.h /usr/include/features.h
./renderer/SE_TextureID.o: /usr/include/sys/cdefs.h
./renderer/SE_TextureID.o: /usr/include/bits/wordsize.h
./renderer/SE_TextureID.o: /usr/include/gnu/stubs.h
./renderer/SE_TextureID.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
./renderer/SE_TextureID.o: /usr/include/sys/types.h /usr/include/bits/types.h
./renderer/SE_TextureID.o: /usr/include/bits/typesizes.h /usr/include/time.h
./renderer/SE_TextureID.o: /usr/include/endian.h /usr/include/bits/endian.h
./renderer/SE_TextureID.o: /usr/include/bits/byteswap.h
./renderer/SE_TextureID.o: /usr/include/sys/select.h
./renderer/SE_TextureID.o: /usr/include/bits/select.h
./renderer/SE_TextureID.o: /usr/include/bits/sigset.h
./renderer/SE_TextureID.o: /usr/include/bits/time.h
./renderer/SE_TextureID.o: /usr/include/sys/sysmacros.h
./renderer/SE_TextureID.o: /usr/include/bits/pthreadtypes.h
./renderer/SE_TextureID.o: /usr/include/alloca.h /usr/include/string.h
./renderer/SE_TextureID.o: /usr/include/stdio.h /usr/include/libio.h
./renderer/SE_TextureID.o: /usr/include/_G_config.h /usr/include/wchar.h
./renderer/SE_TextureID.o: /usr/include/bits/stdio_lim.h
./renderer/SE_TextureID.o: /usr/include/bits/sys_errlist.h
./renderer/SE_TextureID.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
./renderer/SE_TextureID.o: /usr/include/inttypes.h /usr/include/stdint.h
./renderer/SE_TextureID.o: /usr/include/bits/wchar.h SE_Memory.h
./renderer/SE_Renderer.o: ./renderer/SE_Renderer.h SE_Vector.h SE_Common.h
./renderer/SE_Renderer.o: /usr/include/assert.h /usr/include/features.h
./renderer/SE_Renderer.o: /usr/include/sys/cdefs.h
./renderer/SE_Renderer.o: /usr/include/bits/wordsize.h
./renderer/SE_Renderer.o: /usr/include/gnu/stubs.h
./renderer/SE_Renderer.o: /usr/include/gnu/stubs-32.h /usr/include/stdlib.h
./renderer/SE_Renderer.o: /usr/include/sys/types.h /usr/include/bits/types.h
./renderer/SE_Renderer.o: /usr/include/bits/typesizes.h /usr/include/time.h
./renderer/SE_Renderer.o: /usr/include/endian.h /usr/include/bits/endian.h
./renderer/SE_Renderer.o: /usr/include/bits/byteswap.h
./renderer/SE_Renderer.o: /usr/include/sys/select.h
./renderer/SE_Renderer.o: /usr/include/bits/select.h
./renderer/SE_Renderer.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
./renderer/SE_Renderer.o: /usr/include/sys/sysmacros.h
./renderer/SE_Renderer.o: /usr/include/bits/pthreadtypes.h
./renderer/SE_Renderer.o: /usr/include/alloca.h /usr/include/string.h
./renderer/SE_Renderer.o: /usr/include/stdio.h /usr/include/libio.h
./renderer/SE_Renderer.o: /usr/include/_G_config.h /usr/include/wchar.h
./renderer/SE_Renderer.o: /usr/include/bits/stdio_lim.h
./renderer/SE_Renderer.o: /usr/include/bits/sys_errlist.h SE_Matrix.h
./renderer/SE_Renderer.o: SE_Quat.h SE_List.h SE_Element.h SE_String.h
./renderer/SE_Renderer.o: SE_GeometryData.h SE_Spatial.h SE_BoundingVolume.h
./renderer/SE_Renderer.o: SE_Geometry3D.h SE_AABB.h SE_Sphere.h
./renderer/SE_Renderer.o: SE_RenderState.h SE_ResourceManager.h SE_HashMap.h
./renderer/SE_Renderer.o: SE_Script.h ./cscript/acc.h /usr/include/stdint.h
./renderer/SE_Renderer.o: /usr/include/bits/wchar.h ./renderer/SE_TextureID.h
./renderer/SE_Renderer.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
./renderer/SE_Renderer.o: /usr/include/inttypes.h SE_World.h SE_Camera.h
./renderer/SE_Renderer.o: SE_Input.h SE_SaveState.h /usr/include/GL/glu.h
./renderer/SE_Renderer.o: SE_Memory.h SE_Log.h
./cscript/hashmap.o: ./cscript/hashmap.h /usr/include/stdlib.h
./cscript/hashmap.o: /usr/include/features.h /usr/include/sys/cdefs.h
./cscript/hashmap.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
./cscript/hashmap.o: /usr/include/gnu/stubs-32.h /usr/include/sys/types.h
./cscript/hashmap.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
./cscript/hashmap.o: /usr/include/time.h /usr/include/endian.h
./cscript/hashmap.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
./cscript/hashmap.o: /usr/include/sys/select.h /usr/include/bits/select.h
./cscript/hashmap.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
./cscript/hashmap.o: /usr/include/sys/sysmacros.h
./cscript/hashmap.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
./cscript/hashmap.o: /usr/include/assert.h /usr/include/errno.h
./cscript/hashmap.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
./cscript/hashmap.o: /usr/include/asm/errno.h
./cscript/hashmap.o: /usr/include/asm-generic/errno.h
./cscript/hashmap.o: /usr/include/asm-generic/errno-base.h
./cscript/hashmap.o: /usr/include/string.h
./cscript/acc.o: /usr/include/ctype.h /usr/include/features.h
./cscript/acc.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
./cscript/acc.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
./cscript/acc.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
./cscript/acc.o: /usr/include/endian.h /usr/include/bits/endian.h
./cscript/acc.o: /usr/include/bits/byteswap.h /usr/include/errno.h
./cscript/acc.o: /usr/include/bits/errno.h /usr/include/linux/errno.h
./cscript/acc.o: /usr/include/asm/errno.h /usr/include/asm-generic/errno.h
./cscript/acc.o: /usr/include/asm-generic/errno-base.h /usr/include/limits.h
./cscript/acc.o: /usr/include/limits.h /usr/include/bits/posix1_lim.h
./cscript/acc.o: /usr/include/bits/local_lim.h /usr/include/linux/limits.h
./cscript/acc.o: /usr/include/bits/posix2_lim.h /usr/include/stdint.h
./cscript/acc.o: /usr/include/bits/wchar.h /usr/include/stdio.h
./cscript/acc.o: /usr/include/libio.h /usr/include/_G_config.h
./cscript/acc.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
./cscript/acc.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
./cscript/acc.o: /usr/include/sys/types.h /usr/include/time.h
./cscript/acc.o: /usr/include/sys/select.h /usr/include/bits/select.h
./cscript/acc.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
./cscript/acc.o: /usr/include/sys/sysmacros.h
./cscript/acc.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
./cscript/acc.o: /usr/include/string.h /usr/include/unistd.h
./cscript/acc.o: /usr/include/bits/posix_opt.h /usr/include/bits/confname.h
./cscript/acc.o: /usr/include/getopt.h ./cscript/hashmap.h ./cscript/acc.h
./cscript/acc.o: SE_Common.h /usr/include/assert.h SE_Log.h
./cscript/acc.o: /usr/include/sys/mman.h /usr/include/bits/mman.h
./ase/aselib.o: ./ase/aselib.h ./SE_Log.h ./SE_GeometryData.h SE_Common.h
./ase/aselib.o: /usr/include/assert.h /usr/include/features.h
./ase/aselib.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
./ase/aselib.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
./ase/aselib.o: /usr/include/stdlib.h /usr/include/sys/types.h
./ase/aselib.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
./ase/aselib.o: /usr/include/time.h /usr/include/endian.h
./ase/aselib.o: /usr/include/bits/endian.h /usr/include/bits/byteswap.h
./ase/aselib.o: /usr/include/sys/select.h /usr/include/bits/select.h
./ase/aselib.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
./ase/aselib.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
./ase/aselib.o: /usr/include/alloca.h /usr/include/string.h
./ase/aselib.o: /usr/include/stdio.h /usr/include/libio.h
./ase/aselib.o: /usr/include/_G_config.h /usr/include/wchar.h
./ase/aselib.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
./ase/aselib.o: SE_Vector.h ./SE_ResourceManager.h SE_GeometryData.h
./ase/aselib.o: SE_HashMap.h SE_Element.h SE_String.h SE_Script.h
./ase/aselib.o: ./cscript/acc.h /usr/include/stdint.h
./ase/aselib.o: /usr/include/bits/wchar.h ./renderer/SE_TextureID.h
./ase/aselib.o: /usr/include/GL/gl.h /usr/include/GL/glext.h
./ase/aselib.o: /usr/include/inttypes.h ./SE_Memory.h
main.o: /usr/include/stdio.h /usr/include/features.h /usr/include/sys/cdefs.h
main.o: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
main.o: /usr/include/gnu/stubs-32.h /usr/include/bits/types.h
main.o: /usr/include/bits/typesizes.h /usr/include/libio.h
main.o: /usr/include/_G_config.h /usr/include/wchar.h
main.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
main.o: /usr/include/math.h /usr/include/bits/huge_val.h
main.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
main.o: ./ase/aselib.h SE_ResourceManager.h SE_Common.h /usr/include/assert.h
main.o: /usr/include/stdlib.h /usr/include/sys/types.h /usr/include/time.h
main.o: /usr/include/endian.h /usr/include/bits/endian.h
main.o: /usr/include/bits/byteswap.h /usr/include/sys/select.h
main.o: /usr/include/bits/select.h /usr/include/bits/sigset.h
main.o: /usr/include/bits/time.h /usr/include/sys/sysmacros.h
main.o: /usr/include/bits/pthreadtypes.h /usr/include/alloca.h
main.o: /usr/include/string.h SE_GeometryData.h SE_Vector.h SE_HashMap.h
main.o: SE_Element.h SE_String.h SE_Script.h ./cscript/acc.h
main.o: /usr/include/stdint.h /usr/include/bits/wchar.h
main.o: ./renderer/SE_TextureID.h /usr/include/GL/gl.h
main.o: /usr/include/GL/glext.h /usr/include/inttypes.h SE_Spatial.h
main.o: SE_BoundingVolume.h SE_Geometry3D.h SE_Quat.h SE_Matrix.h SE_AABB.h
main.o: SE_Sphere.h SE_RenderState.h SE_List.h SE_Log.h SE_World.h
main.o: SE_Camera.h SE_Input.h SE_SaveState.h cscript/acc.h
main.o: /usr/include/GL/glu.h /usr/include/ctype.h /usr/include/dlfcn.h
main.o: /usr/include/bits/dlfcn.h ./renderer/SE_Renderer.h SE_Memory.h
main.o: SE_Init.h /usr/include/SDL/SDL.h /usr/include/SDL/SDL_main.h
main.o: /usr/include/SDL/SDL_stdinc.h /usr/include/SDL/SDL_config.h
main.o: /usr/include/SDL/SDL_platform.h /usr/include/strings.h
main.o: /usr/include/iconv.h /usr/include/SDL/begin_code.h
main.o: /usr/include/SDL/close_code.h /usr/include/SDL/SDL_audio.h
main.o: /usr/include/SDL/SDL_error.h /usr/include/SDL/SDL_endian.h
main.o: /usr/include/SDL/SDL_mutex.h /usr/include/SDL/SDL_thread.h
main.o: /usr/include/SDL/SDL_rwops.h /usr/include/SDL/SDL_cdrom.h
main.o: /usr/include/SDL/SDL_cpuinfo.h /usr/include/SDL/SDL_events.h
main.o: /usr/include/SDL/SDL_active.h /usr/include/SDL/SDL_keyboard.h
main.o: /usr/include/SDL/SDL_keysym.h /usr/include/SDL/SDL_mouse.h
main.o: /usr/include/SDL/SDL_video.h /usr/include/SDL/SDL_joystick.h
main.o: /usr/include/SDL/SDL_quit.h /usr/include/SDL/SDL_loadso.h
main.o: /usr/include/SDL/SDL_timer.h /usr/include/SDL/SDL_version.h
