CC = g++
RM = rm -f
SRCS = SE_Vector.c \
		   SE_Math.c \
		   SE_Matrix.c \
		   SE_Quat.c \
		   SE_Memory.c \
		   SE_Element.c \
		   SE_String.c \
		   SE_List.c \
		   SE_HashMap.c \
		   SE_Log.c \
		   SE_Utils.c \
		   SE_GeometryData.c \
		   SE_Spatial.c \
		   SE_BoundingVolume.c \
		   SE_ResourceManager.c \
		   SE_Geometry3D.c \
		   SE_RenderState.c \
		   SE_World.c \
		   SE_Camera.c \
		   SE_Script.c \
		   SE_Input.c \
		   SE_Init.c \
		   SE_SaveState.c \
		   SE_AABB.c \
		   SE_Sphere.c \
		   SE_OBB.c \
		   SE_GeometryIntersect.c \
		   ./renderer/SE_TextureID.c \
		   ./renderer/SE_Renderer.c \
		   ./cscript/hashmap.c \
		   ./cscript/acc.c \
		   ./ase/aselib.c \
		   main.c

OBJ_FILE = $(SRCS:.c=.o)
OUTPUT_NAME = seapp
INCLUDE_PATH = -I./ -I../ -I/usr/include -I/usr/include/SDL
INPUT_LIB = -L/usr/lib -lm -lGL -lGLU `sdl-config --libs`
CFLAGS = -g -DDEBUG $(INCLUDE_PATH)
all: $(OBJ_FILE) depend
	$(CC) $(INPUT_LIB) $(OBJ_FILE) -o $(OUTPUT_NAME)
depend: 
	makedepend -- $(CFLAGS) -- $(SRCS)
%.o: %.c
	$(CC) -c $(CFLAGS) $< -o $@ 
clean:
	$(RM) $(OBJ_FILE) $(OUTPUT_NAME)
# DO NOT DELETE

